baseURL = "https://Chesszyh.github.io/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

staticDir = ["static", "static"]

theme = "Niello"

[module]
[module.hugoVersion]
min = "0.100.0"
[languages]
[languages.en]
title = "{CodeTrace} - Discover Issues, Share Solutions."
languageCode = "en-us"
LanguageName = "ğŸ‡ºğŸ‡¸EN"
contentDir = "content/en"
weight = 1
[[languages.en.menus.main]]
name = 'Home'
pageRef = '/'
weight = 1
[[languages.en.menus.main]]
name = 'Categories'
pageRef = '/categories'
weight = 2
[[languages.en.menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 3
[[languages.en.menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 4
[languages.zh]
title = "idk."
languageCode = "zh-cn"
LanguageName = "ğŸ‡¨ğŸ‡³CN"
contentDir = "content/zh"
weight = 2
[[languages.zh.menus.main]]
name = 'é¦–é¡µ'
pageRef = '/'
weight = 1
[[languages.zh.menus.main]]
name = 'æ–‡ç« åˆ†ç±»'
pageRef = '/categories'
weight = 2
[[languages.zh.menus.main]]
name = 'æ ‡ç­¾'
pageRef = '/tags'
weight = 3
[[languages.zh.menus.main]]
name = 'è”ç³»æˆ‘'
pageRef = '/contact'
weight = 4

[params]
[params.google]
google_ad_client = ""
ga4 = ""
[params.bannershowcase]
categories = ["AI"]
limit = 2
[params.email]
contact = "chesszyh987@gmail.com"
[params.ignore]
categories = ["privacy", "terms", "archives", "cookie"]
[params.license]
copyright = "&#xA9; 2019 ~ 2025 by guangmean. All Rights Reserved."
[params.share]
sharethis = ""
[params.disqus]
shortname = ""

[outputs]
home = ["HTML", "JSON"]
